name: 'dbt_premierleague'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

# vars:
#  dbt_analytics:
#    gcp_project_id: # Here you can insert your project id from google cloud, it is not necessary for Kestra,
                    # But if you want to do something else with this project you may need to add it here.

models:
  dbt_premierleague:
    core:
          materialized: table