version: 2

models:
  - name: fct_ranking
    description: "Dimensional table containing geolocation data for sellers."
    columns:
      - name: season
        data_type: string
        description: "Unique identifier for the seller."

      - name: date
        data_type: date
        description: "Unique identifier for the seller."
      
      - name: team
        data_type: string
        description: "Postal code prefix of the seller's location."

      - name: side
        data_type: string
        description: "Postal code prefix of the seller's location."
      
      - name: points
        data_type: int64
        description: "Latitude coordinate of the seller's location."

      - name: goals_scored
        data_type: int64
        description: "Longitude coordinate of the seller's location."

      - name: goals_conceded
        data_type: int64
        description: "State where the seller is located."

      - name: goal_difference
        data_type: int64
        description: "State where the seller is located."

  - name: fct_goals_scored
    description: "Dimensional table capturing marketing funnel data for potential sellers."
    columns:
      - name: season
        data_type: string
        description: "Unique identifier for the Marketing Qualified Lead (MQL)."

      - name: team
        data_type: string
        description: "Unique identifier for the seller who progressed through the marketing funnel."

      - name: total_goals_scored
        data_type: string
        description: "Unique identifier for the seller who progressed through the marketing funnel."