version: 2

sources:
  - name: zoomcamp
    database: "{{ var('dbt_premierleague')['gcp_project_id'] }}"
    schema: "{{ var('dbt_premierleague')['schema'] }}"    #bigquery dataset source
    tables:
      - name: premierleague_dataset     #bigquery dataset table
        description: "english premier league match statistics"

  - models:
    - name: stg_home
      description: "Courses enrolled in that particular month."
      columns:
        - name: season
          data_type: string
          description: "The year and month of the courses extraction. Example: 2025-03."
          tests:
            - not_null:
                severity: warn

        - name: date
          data_type: date
          description: "Dataset upload date. Example: 2025-03-19."
          tests:
            - not_null:
                severity: warn

        - name: team
          data_type: string
          description: "company providing the course. Example: AFTRAL."

        - name: side
          data_type: string
          description: "Certification Title. Example: Certificate of aptitude for safe driving (CACES) Recommendation 482 category B1: Sequential movement extraction equipment."

        - name: goals_scored
          data_type: int64
          description: "Certification code corresponding to certification_title. Example: 106655."

        - name: goals_conceded
          data_type: int64
          description: "National Directory of Professional Certifications Code. Example: -1 (Because it has code_rs)."

        - name: result
          data_type: string
          description: "Certifications listed in the RS inventory. Example: 7041."

    - name: stg_away
      description: "Courses enrolled in that particular month."
      columns:
        - name: season
          data_type: string
          description: "The year and month of the courses extraction. Example: 2025-03."
          tests:
            - not_null:
                severity: warn

        - name: date
          data_type: date
          description: "Dataset upload date. Example: 2025-03-19."
          tests:
            - not_null:
                severity: warn

        - name: team
          data_type: string
          description: "company providing the course. Example: AFTRAL."

        - name: side
          data_type: string
          description: "Certification Title. Example: Certificate of aptitude for safe driving (CACES) Recommendation 482 category B1: Sequential movement extraction equipment."

        - name: goals_scored
          data_type: int64
          description: "Certification code corresponding to certification_title. Example: 106655."

        - name: goals_conceded
          data_type: int64
          description: "National Directory of Professional Certifications Code. Example: -1 (Because it has code_rs)."

        - name: result
          data_type: string
          description: "Certifications listed in the RS inventory. Example: 7041."
      