version: 2

sources:
  - name: zoomcamp
    database: "{{ var('dbt_premierleague')['gcp_project_id'] }}"
    schema: "{{ var('dbt_premierleague')['schema'] }}"    #bigquery dataset source
    tables:
      - name: premierleague_dataset     #bigquery dataset table
        description: "english premier league match statistics"