version: 2

sources:
  - name: zoomcamp
    database: "{{ var('dbt_analytics')['gcp_project_id'] }}"
    schema: capstone_dataset_2025      #bigquery dataset source
    tables:
      - name: premierleague_dataset     #bigquery dataset table
        description: "english premier league match statistics"

#   - name: dbt_premierleague_analytics   
#     database: "{{ var('dbt_premierleague')['gcp_project_id'] }}"
#     schema: dbt_premierleague_analytics  #bigquery dataset destination, will be generated after kestra run
#     tables:
#       - name: goals
#         description: "check sample data"

# sources:
#   - name: core
#     database: "{{ var('dbt_premierleague')['gcp_project_id'] }}"
#     schema: dbt_premierleague_analytics
#       # loaded_at_field: record_loaded_at
#     tables:
#       - name: goals
#          # freshness:
#            # error_after: {count: 6, period: hour}